sonar.projectKey=contact-management-frontend
sonar.projectName=Contact Management Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/src/assets/**

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info