wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.16/apache-maven-3.9.16-bin.zip
distributionSha256Sum=5AF3B743DD8B876B5C45DA33B676251E5F1687712644ABB4EE519CA56E1D89CE