spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=contact_management;encrypt=true;trustServerCertificate=true;authentication=SqlPassword
spring.datasource.username=Fuzail
spring.datasource.password=Venom12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG
jwt.secret=VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdTZWNyZXRLZXlGb3JKV1QxMjM0NTY3ODkw
jwt.expiration-ms=3600000
server.error.include-message=always
server.error.include-stacktrace=always
logging.level.org.springframework.web=DEBUG

